apiVersion: aiops.crossplane.io/v1alpha1
kind: Dependency
metadata:
  name: dependency-test
spec:
  forProvider:
    configurableField: test
    airGap:
      isAirGap: true
      privateRepo: dents1.fyre.ibm.com:5000
  providerConfigRef:
    name: example
