apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement-key
  namespace: crossplane-system
type: Opaque
data:
  credentials: eyJhdXRocyI6eyJjcC5pY3IuaW8iOnsidXNlcm5hbWUiOiJjcCIsInBhc3N3b3JkIjoiZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcGMzTWlPaUpKUWswZ1RXRnlhMlYwY0d4aFkyVWlMQ0pwWVhRaU9qRTJNREkxTlRNMk5ESXNJbXAwYVNJNklqUTJabUV4TVdVeVpHRXhaVFJoWXpBNVpqSmtaVE01TVRneU1tTXlPR1ptSW4wLmVDUnZhdE1XcVpCbnRqU2VZOFpJUXpfMUdNRzJtd1pTbUEyaDVRV2tpSjQiLCJhdXRoIjoiWTNBNlpYbEthR0pIWTJsUGFVcEpWWHBKTVU1cFNqa3VaWGxLY0dNelRXbFBhVXBLVVdzd1oxUlhSbmxoTWxZd1kwZDRhRmt5VldsTVEwcHdXVmhSYVU5cVJUSk5SRWt4VGxSTk1rNUVTWE5KYlhBd1lWTkpOa2xxVVRKYWJVVjRUVmRWZVZwSFJYaGFWRkpvV1hwQk5WcHFTbXRhVkUwMVRWUm5lVTF0VFhsUFIxcHRTVzR3TG1a
